stages:
  join:
    cmd: >
      lyscripts data join
      --inputs
      data/2021-usz-oropharynx.csv
      data/2021-clb-oropharynx.csv
      data/2023-clb-multisite.csv
      data/2023-isb-multisite.csv
      data/2023-hvh-oropharynx.csv
      --output
      data/joined.csv
    deps:
      - data/2021-usz-oropharynx.csv
      - data/2021-clb-oropharynx.csv
      - data/2023-clb-multisite.csv
      - data/2023-isb-multisite.csv
      - data/2023-hvh-oropharynx.csv
    outs:
      - data/joined.csv

  filter:
    cmd: >
      lyscripts data filter
      data/joined.csv
      data/filtered.csv
      --include-subsites
      C01 C02 C03 C04 C05 C06 C09 C10
    deps:
      - data/joined.csv
    outs:
      - data/filtered.csv

  enhance:
    cmd: >
      lyscripts data enhance data/filtered.csv data/enhanced.csv
    deps:
      - data/filtered.csv
    params:
      - modalities
    outs:
      - data/enhanced.csv

  plot_prevalence_by_subsite:
    cmd: >
      python scripts/prevalence_by_subsite.py
      --input data/enhanced.csv
      --params params.yaml
      --output figures/prevalence_by_subsite.svg
    deps:
      - data/enhanced.csv
      - scripts/prevalence_by_subsite.py
    params:
      - barplot_kwargs
    outs:
      - figures/prevalence_by_subsite.svg
