# Define sensitivity & specificity for diagnostic modalities. This is necessary for the
# data enhancement script from `lyscripts`
modalities:
  CT: [0.76, 0.81]
  MRI: [0.63, 0.81]
  PET: [0.86, 0.79]
  FNA: [0.98, 0.80]
  diagnostic_consensus: [0.86, 0.81]
  pathology: [1.0, 1.0]
  pCT: [0.86, 0.81]
  max_llh: [1.0, 1.0]

# Keyword arguments for the barplot created by `prevalence_by_subsite.py`
barplot_kwargs:
  width: 0.9
  zorder: 2